### ISSUE TITLE
서킷브레이커(Circuit Breaker)

### ISSUE THREAD

**Issue by hanchy-git** [hanchy-git/carsharing#11]

**Comment by HanSungHo** [comment]
1. Istio 설치
$ curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.1 TARGET_ARCH=x86_64 sh -
$ cd istio-1.7.1
$ export PATH=$PWD/bin:$PATH
$ istioctl install --set profile=demo
1-1.  설치확인
$ kubectl get pod -n istio-system

2. Istio 모니터링 툴 설치
vi samples/addons/kiali.yaml

4라인의
apiVersion: apiextensions.k8s.io/v1beta1 을
apiVersion: apiextensions.k8s.io/v1으로 수정
kubectl apply -f samples/addons

2-2. 모니터링 툴 설정
kubectl edit svc kiali -n istio-system
:%s/ClusterIP/LoadBalancer/g
:wq!

2-3. 모니터링 시스템 접속
EXTERNAL-IP:20001 (admin/admin)

3. 네임스페이스 생성
kubectl create namespace istio-test-ns
kubectl label namespace istio-test-ns istio-injection=enabled

label에 istio-injection enabled 확인
![image](https://user-images.githubusercontent.com/34739884/122332872-2cd04480-cf72-11eb-8372-03583810bee9.png)

4 namespace로 서비스 재배포

kubectl create deploy gateway --image=hsh00.azurecr.io/gateway:latest -n istio-test-ns
kubectl expose deploy gateway --type="LoadBalancer" --port=8080 -n istio-test-ns
나머지 동일

생성된 Container 확인
![image](https://user-images.githubusercontent.com/34739884/122333060-85074680-cf72-11eb-96d6-f295680dbb97.png)
Gateway 정상확인
![image](https://user-images.githubusercontent.com/34739884/122333120-a0725180-cf72-11eb-8843-fd47274d09ec.png)


5. Circuit Breaker Destination Rule 생성

kubectl apply -f - <<EOF
  apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: dr-httpbin
    namespace: istio-test-ns
  spec:
    host: gateway
    trafficPolicy:
      connectionPool:
        http:
          http1MaxPendingRequests: 1
          maxRequestsPerConnection: 1
EOF


5-1. Siege Client 접속
kubectl exec -it pod/[객체] -n istio-cb-ns -- /bin/bash


정상 동작일떄 확인
siege -c1 -t30S -v --content-type "application/json" 'http://52.231.99.165:8080/reservations POST {"carId": "g90", "amonut": "1"}'
![image](https://user-images.githubusercontent.com/34739884/122333332-efb88200-cf72-11eb-92df-a5e3e396e113.png)

Circuit Breaker 동작 확인
siege -c2 -t50S -v --content-type "application/json" 'http://52.141.63.150:8080/reservations POST {"carId": "g80", "amonut": "1"}'
![image](https://user-images.githubusercontent.com/34739884/122333382-05c64280-cf73-11eb-97f8-658e5dc304f0.png)


6.모니터링 시스템 (kiali)에서 확인
![image](https://user-images.githubusercontent.com/34739884/122333511-41610c80-cf73-11eb-8cf8-47b16dd2941b.png)

**Comment by jychung88** [comment]
Istio 설치
$ curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.1 TARGET_ARCH=x86_64 sh -
$ cd istio-1.7.1
$ export PATH=$PWD/bin:$PATH
$ istioctl install --set profile=demo
1-1. 설치확인
$ kubectl get pod -n istio-system

Istio 모니터링 툴 설치
vi samples/addons/kiali.yaml

4라인의
apiVersion: apiextensions.k8s.io/v1beta1 을
apiVersion: apiextensions.k8s.io/v1으로 수정
kubectl apply -f samples/addons

2-2. 모니터링 툴 설정
kubectl edit svc kiali -n istio-system
:%s/ClusterIP/LoadBalancer/g
:wq!

2-3. 모니터링 시스템 접속
EXTERNAL-IP:20001 (admin/admin)

네임스페이스 생성
kubectl create namespace istio-test-ns
kubectl label namespace istio-test-ns istio-injection=enabled
label에 istio-injection enabled 확인
image

4 namespace로 서비스 재배포

kubectl create deploy gateway --image=hsh00.azurecr.io/gateway:latest -n istio-test-ns
kubectl expose deploy gateway --type="LoadBalancer" --port=8080 -n istio-test-ns
나머지 동일

생성된 Container 확인
image
Gateway 정상확인
image

Circuit Breaker Destination Rule 생성
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
name: dr-httpbin
namespace: istio-test-ns
spec:
host: gateway
trafficPolicy:
connectionPool:
http:
http1MaxPendingRequests: 1
maxRequestsPerConnection: 1
EOF

5-1. Siege Client 접속
kubectl exec -it pod/[객체] -n istio-cb-ns -- /bin/bash

정상 동작일떄 확인
siege -c1 -t30S -v --content-type "application/json" 'http://52.231.99.165:8080/reservations POST {"carId": "g90", "amonut": "1"}'
image

Circuit Breaker 동작 확인
siege -c2 -t50S -v --content-type "application/json" 'http://52.141.63.150:8080/reservations POST {"carId": "g80", "amonut": "1"}'
image

6.모니터링 시스템 (kiali)에서 확인
